### ISSUE TITLE
User needs to be prompted to create a channel

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#1]
When the wallet pays (or creates an invoice), if the user has not created an asset channel, the user needs to be prompted to create a channel. Because people don't know the principle of Lightning Network, just want to use a convenient wallet. So this is from a user perspective.

**Comment by neocarmack** [comment]
![053f9021ac364cb9f4854fb31a54f7c](https://user-images.githubusercontent.com/15964933/216529477-8817f021-6c95-4c4e-ab51-2940368506ae.png)

**Comment by neocarmack** [comment]
> ![053f9021ac364cb9f4854fb31a54f7c](https://user-images.githubusercontent.com/15964933/216529477-8817f021-6c95-4c4e-ab51-2940368506ae.png)

This will be a sample screen, which helps user to go to create a lightning channel.

**Comment by healergyl** [comment]
asdasdasdasd

**Comment by progressorTCH** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by saiful112233** [comment]
Hiii

Pada tanggal Jum, 3 Feb 2023 13.38, 童昌辉 ***@***.***> menulis:

**Comment by healergyl** [comment]
resolved
