### ISSUE TITLE
Should do the backup automatically for a few situations

### ISSUE THREAD

**Issue by iamgamelover** [omnilaboratory/OBAndroid#100]
1) The channel is created or closed successfully.
2) A transaction is finished in a channel.
3) The balance of the wallet address is changed.

**Comment by wxf4150** [comment]
backup should be more frequently.

app can  subscribe   lnd's SubscribeChannelBackups  stream .
when app receive any event ,app  make a backup.

Alternatively, refer to the Breeze backup implementation； I'm not very familiar with Breeze's code;

**Comment by neocarmack** [comment]
fixed

**Comment by neocarmack** [comment]
fixed
