### ISSUE TITLE
The mainnet and testnet editions share the same backup file names, which conflicts each other. 

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#105]
The backup file names are: channel.db, wallet.db in google drive and local device. The mainnet and testnet edtions share the same backup file names, which conflicts each other if i installed both.

**Comment by iamgamelover** [comment]
Should has 2 ways to solve that:

1) Different name - Mainnet: channel.db, wallet.db. Testnet: channel-testnet.db, wallet-testnet.db.
2) Put files into diff paths - \mainnet\ and \testnet\

**Comment by iamgamelover** [comment]
Another thing that needs to solve for installing both versions on one phone.
There should be a different package in code like this
1) com.omni.wallet
2) com.omni.wallet_testnet

**Comment by healergyl** [comment]
resolved
