### ISSUE TITLE
Keep one single edition backup file on Google drive

### ISSUE THREAD

**Issue by iamgamelover** [omnilaboratory/OBAndroid#111]
Currently, there are huge backup files on Google drive, because generates new files every backup.
Keeping one single edition backup file would be better.

**Comment by wxf4150** [comment]
A backup contains two files, wallet.db channel, approximately 600k; After gzip compression, 150kb



Can you save the last 5-10 backups? This will make it easier to identify the backup time points.

The backup version is very important, and any expired version of channeldb cannot be used.

**Comment by healergyl** [comment]
resolved
