### ISSUE TITLE
recover wallet.db address

### ISSUE THREAD

**Issue by wxf4150** [omnilaboratory/OBAndroid#112]
after  use  my pc's wallet.db channel.db  recover obdMobile app.
in the app ,my obdMobile's wallet address changed, is not my old address.

obdMobile's  first  wallet address is generate when first call  newaddress api , and reocord in the wallet.db.

 app should not  invoke newaddress the when recover,  this will generate another address.
 app can use  getinfo or listrecaddress api  to get the old address in the wallet.db。

**Comment by healergyl** [comment]
app is currently using getinfo or listrecaddress API to get old address in wallet.db.

**Comment by healergyl** [comment]
resolved
