### ISSUE TITLE
Program exception while creating a channel

### ISSUE THREAD

**Issue by SergeyShirin** [omnilaboratory/OBAndroid#113]
![Screenshot_20230724_110639_com huawei android launcher](https://github.com/omnilaboratory/OBAndroid/assets/57345478/5eb1f6b6-f520-43f7-9043-6ca92982d17c)
I downloaded OBWallet and tried to open some channels. But when I press “Create” (to create a channel), I always get an error: “Sorry, the program encountered an exception and is about to exit”.

I tried two versions: 0.1.5 and 0.1.3. 
I used them on two smartphones: Pixel 5a and Honor 9. 
I tested both mainnet and testnet.
There is the same issue in all the cases.

**Comment by neocarmack** [comment]
fixed

**Comment by neocarmack** [comment]
This exception is caused by an input widget and has been fixed
