### ISSUE TITLE
MUST lock the wallet if there is no activities for like 5 minuts. 

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#15]
It won't lock even if I don't use it for a few days.

**Comment by progressorTCH** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by progressorTCH** [comment]
The function modification has been completed, for details, please refer to [dd59d11c891ab9d1d091616313ac2775e8f8f9ff](https://github.com/omnilaboratory/OBAndroid/commit/dd59d11c891ab9d1d091616313ac2775e8f8f9ff)
