### ISSUE TITLE
When sending a lucky packet, allow the sender to edit a short message to those who collect the packet. 

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#17]
When sending a lucky packet, allow the sender to edit a short message to those who collect the packet.  The default message is "Wish you good health". The number limit of the words is 24.

**Comment by saiful112233** [comment]
How to collect?

Pada tanggal Sen, 6 Mar 2023 16.48, Neo Carmack ***@***.***>
menulis:
