### ISSUE TITLE
"Reserved wallet balance invalidated" when creating a channel

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#21]
![image](https://user-images.githubusercontent.com/15964933/224724365-67bbfc02-ac9d-4d6f-b1ca-e2725e8e7397.png)

```
code = Unknown desc =  reserved wallet balance invalidated: transaction would leave insufficient funds for free bumping anchor channel closings(see debug log for details)
```

**Comment by neocarmack** [comment]
My wallet has 0.0002 Bitcoin and 200 Dollar in balance.

**Comment by saiful112233** [comment]
Waiting download

Pada tanggal Sen, 13 Mar 2023 21.07, Neo Carmack ***@***.***>
menulis:

**Comment by healergyl** [comment]
The balance of btc in the wallet is insufficient
