### ISSUE TITLE
Change some text at the page that leads user to create a channel

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#24]
![image](https://user-images.githubusercontent.com/15964933/225350875-ca79d2cb-0396-489f-be1f-e996d8aa50b4.png)

Change to:  

"You have not created a channel for this asset, please create at least one channel with enough funds, and then continue to proceed (pay, create an invoice, collect a gift, etc)."

**Comment by healergyl** [comment]
resolved
