### ISSUE TITLE
The keyboard blocks the text box, making it impossible to click the text box on the next line to enter

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#25]
![image](https://user-images.githubusercontent.com/15964933/225353173-c2ea1a02-40c7-4298-ad5d-9054232ec1f4.png)

**Comment by progressorTCH** [comment]
repair at [24d7709c8e376328b8183ca8d3d1be12eb2a603f](https://github.com/omnilaboratory/OBAndroid/commit/24d7709c8e376328b8183ca8d3d1be12eb2a603f)
