### ISSUE TITLE
an invoice can be paid twice

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#26]
Steps to reproduce:

Me: create an invoice, and close wallet(keep offline).

Payer 1: scan to pay the invoice, succeed. And I received the payment. 

Two hours later:

Payer 2 scan to pay the same invoice, succeed. And i did not receive the second payment(which is correct at the payee side). The money is collected by the liquidity node. This is wrong. This payment MUST not be successful. Payer 2 MUST get information that the invoice can not be paid twice.

**Comment by healergyl** [comment]
resolved
