### ISSUE TITLE
Change "BACK" to "SAVE"

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#30]
![image](https://user-images.githubusercontent.com/15964933/225361510-38e16524-7f26-49b1-ae04-da87248deb05.png)

**Comment by neocarmack** [comment]
Because if go back, will create another lucky packet. The user will pay twice. Which is confusing to users. 

Change to "SAVE" to save the popup screen to local album. The icon is also changed.

**Comment by healergyl** [comment]
resolved
