### ISSUE TITLE
The closing channel transaction blocks the whole application. 

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#36]
![4305cc37bfe7540d0c07d245082ff36](https://user-images.githubusercontent.com/15964933/225532649-39a8657a-2e05-4a60-b517-649995027aa6.jpg)

**Comment by neocarmack** [comment]
After the transaction is sent successfully, it should quickly return to the channel list page instead of staying on this waiting page, causing me to be unable to do any other operations.

**Comment by healergyl** [comment]
resolved

**Comment by neocarmack** [comment]
It happened again. @healergyl

**Comment by neocarmack** [comment]
And the dollars in the channel were not sent back to the wallet address.

**Comment by healergyl** [comment]
resolved
