### ISSUE TITLE
The text format is messed up

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#4]
![Screenshot_20230205_010831 (1)](https://user-images.githubusercontent.com/15964933/216781393-05baca3f-d609-400c-afdf-81a31b7d5d38.jpg)

**Comment by progressorTCH** [comment]
repair with https://github.com/omnilaboratory/OBAndroid/commit/90bf63fe578177b356f8e555ba1ef6e384c0dbc1
