### ISSUE TITLE
Error found when sending Dollar

### ISSUE THREAD

**Issue by progressorTCH** [omnilaboratory/OBAndroid#49]
![image](https://user-images.githubusercontent.com/52437247/227844356-2b303787-b270-4759-b3cc-ac033b6a75ad.png)

**1. Entering 20 digits after the decimal point will not report an error. Appropriate prompt information needs to be added here, and local verification is required before calling the interface.**
**2. The pop-up window opened by dollar, the token of the default transaction is not dollar.**
**3. Close the confirmation window after clicking send, the amount may be changed to the BTC amount, and the balance is incorrect.**

**Comment by healergyl** [comment]
resolved
