### ISSUE TITLE
Error found when creating Dollar channel

### ISSUE THREAD

**Issue by progressorTCH** [omnilaboratory/OBAndroid#50]
![image](https://user-images.githubusercontent.com/52437247/227846642-19064232-e7ab-4e03-9144-14db107d7977.png)

**1. The text is too long causing the text to overlap**
**2. The content entered by memo is not judged before calling the interface, and there is no input limit**
**3. Is it because the estimated value of the channel creation fee is too large, and the channel cannot be created when the balance is still 0.0003**

**Comment by healergyl** [comment]
resolved
