### ISSUE TITLE
Error found when claiming the lucky packet

### ISSUE THREAD

**Issue by progressorTCH** [omnilaboratory/OBAndroid#53]
**1. Receiving red envelopes can only be received by scanning the code. Do you want to add the function of filling in the form to receive red envelopes?**

![image](https://user-images.githubusercontent.com/52437247/227850111-f0f0a5cf-8d41-44d6-a1db-e526271fe196.png)

**2. When receiving a lucky packet, the copywriting is too confusing when I make a mistake, and I don’t know the meaning**

**Comment by healergyl** [comment]
resolved
