### ISSUE TITLE
Grammar & Spelling Mistake 

### ISSUE THREAD

**Issue by niteshk1988** [omnilaboratory/OBAndroid#64]
On the home screen , it's mentioned DEPOSITE YOUR WALLET, it should be either " DEPOSIT TO YOUR WALLET" or " FUND YOUR WALLET" 

![2023-03-28 11 58 08](https://user-images.githubusercontent.com/129135443/228133703-62dc982d-b084-407c-bfe3-81a146b0064c.jpg)

**Comment by healergyl** [comment]
resolved
