### ISSUE TITLE
Closing the channel on the main network is always loading

### ISSUE THREAD

**Issue by progressorTCH** [omnilaboratory/OBAndroid#74]
![b272c1ab96c5f31556bedcf317b3c9f](https://user-images.githubusercontent.com/52437247/231670254-d5599934-3e10-47d7-a9a3-2f5fd61073ce.jpg)
Stayed on the loading page for 6 minutes before submitting a question

**Comment by wxf4150** [comment]
i reproduct the issue on regtest: any btc-channel on regtest/testnet which  close use  Ob_SafeBox_CloseChannel will trigger this issue.
Ob_SafeBox_CloseChannel is only can used by  asset-Channel. 
btc-channel should use the old CloseChannel function.


the btc-coin on this channel will lost.
channel which close fail , it's state will be close-pendding, without any api can  reocover the state to active, 　it difficult to reocover the state to active.

**Comment by progressorTCH** [comment]
When I close the channel about USDT, the loading dialog is always here. Before I say this, the loading page has existed for more than 8 minutes。
I checked the code, and the code already requires the "Ob_SafeBox_CloseChannel" method to be used when closing the "assets-channel".
![image](https://user-images.githubusercontent.com/52437247/232987127-1adb1d44-9725-4386-9404-14e3e79fcddf.png)

**Comment by wxf4150** [comment]
i have got the server  log  "unable to process close msg: not all signatures empty on failed checkmultisig"
signatures err, it's difficulty to check.

i will check on regtest later

**Comment by healergyl** [comment]
resolved
