### ISSUE TITLE
By default, "eyes" needs to be closed, unless the user changes the state of "eyes" to open.

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#75]
By default, "eyes" needs to be closed, unless the user changes the state of "eyes" to open.

**Comment by neocarmack** [comment]
Initially, the password should be hidden from public view, and only at will I can show it

**Comment by progressorTCH** [comment]
solove the issues by [here](https://github.com/omnilaboratory/OBAndroid/commit/9f4f9400fe083ab88f90a011ea19ced54dae8a93)
