### ISSUE TITLE
You can pay for invoices you create

### ISSUE THREAD

**Issue by progressorTCH** [omnilaboratory/OBAndroid#77]

**Comment by wxf4150** [comment]
app will  decode invoice  before payment,app can check 'invoice.dest' for SelfPayment .
a another method set AllowSelfPayment field on sendPaymentV2 grpc parameter.

**Comment by wxf4150** [comment]
pay self invoice is normal function .
sendPaymentV2's grpc-parameter AllowSelfPayment default value is false, SelfPayment is disable default.

> "invoice you create"?

the invoice is create by oblnd-addInvoice grpc-api?    

the invoice is create by by our coud server for you?    this type invoice is coud server's invoice. and  "invoice.dest" is server's pubkey,not your pubkey . 

what type invoice you create?

**Comment by healergyl** [comment]
dest is the pubkey of the payment proxy node, and it is impossible to determine whether the invoice was created by itself.

**Comment by wxf4150** [comment]
now app's all invoice id  created  by  coud server. this type invoice  is server's invoice.

if app want to disable pay to  this type invoice ,app can: 
1)when app receive the invoice ceated by server, app can  record the invoice's paymentHash to app local storage .

2)next time , when pay some invoice, check if the invoice's paymentHash  is in local storage, if true app stop payment Invoke

is  it easy ?

**Comment by healergyl** [comment]
There is a situation:

1. After creating the invoice, save the hash and then uninstall the app.

2. After reinstalling the app, the check is invalid, so the previous invoice can also be paid again.

**Comment by wxf4150** [comment]
> After creating the invoice, save the hash and then uninstall the app.

> After reinstalling the app, the check is invalid, so the previous invoice can also be paid again.
it 's a stupid situation.

when  uninstall app,  walletdb is gone ,  all Channel is gone, all local invoices gone, all local trancation record gone. 
after reinstalling the app, the walletdb is all most new:without any channel, without any invoices;   the invoice before uninstall will have no relation with you, and who give you the old invoice.  
 after reinstalling  ,if you need receive new payment ,make cloud server create new invoice for you .

**Comment by healergyl** [comment]
resolved
