### ISSUE TITLE
Unable to transfer all the balance in the channel out

### ISSUE THREAD

**Issue by progressorTCH** [omnilaboratory/OBAndroid#78]
![image](https://user-images.githubusercontent.com/52437247/232466307-763454e0-074c-4d92-b048-daededa32a92.png)
![image](https://user-images.githubusercontent.com/52437247/232466328-7b7a9831-a98c-4de8-95c4-effa4eff73f0.png)
![image](https://user-images.githubusercontent.com/52437247/232466485-f653593d-a0a9-4476-ac9d-8ae001105eb4.png)

**Comment by healergyl** [comment]
resolved

**Comment by healergyl** [comment]
resolved
