### ISSUE TITLE
Fee issues when creating a channel

### ISSUE THREAD

**Issue by progressorTCH** [omnilaboratory/OBAndroid#85]
The default "slow" fee does not match the selected "slow" fee. The difference between "slow" fee and "medium" fee is too small, and the difference between "medium" fee and "slow" fee is too large. Do you need to adjust it?
Regarding the selection of "blocks", select each "block" option, the general rules are as follows:
1-2 are the same, 3 are the same 1, 4 are the same 1, 5-11 are the same, 12-18 are the same, 19-50 are the same
**The details are as follows：**
![微信图片_20230418160743](https://user-images.githubusercontent.com/52437247/232713923-5cbc1bb9-78c7-4c42-b446-c83cc42cbc0b.png)
![微信图片_202304181607431](https://user-images.githubusercontent.com/52437247/232713932-28c96cb1-e553-46d2-ae2a-8d0f1f7e1261.png)
![微信图片_202304181607432](https://user-images.githubusercontent.com/52437247/232713936-febb8eee-6eb2-4ede-b3fd-7791f4f32f36.png)
![微信图片_202304181607433](https://user-images.githubusercontent.com/52437247/232713940-97f505d6-f035-47d6-8d3c-0595ea3f7738.png)
![微信图片_202304181607434](https://user-images.githubusercontent.com/52437247/232713941-75b9898a-5577-4b72-8e56-9bc845590ca7.png)

**Comment by wxf4150** [comment]
the fee base data here: https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json
today data
```json
{
  "current_block_hash": "00000000000000000000eb3a6d9bf922f5f96bb47c856da4ca0da7af50610dc9",
  "fee_by_block_target": {
    "2": 22168,
    "3": 10064,
    "4": 5980,
    "5": 2992,
    "12": 2260,
    "20": 2104
  }
}
```

tx with  confirms bigger than 20, example 25,  will select  ("20": 2104) as gas-fee config . 
  

fee data sevral days ago.
![截图 2023-04-11 20-10-29](https://user-images.githubusercontent.com/5011771/232705827-bf46d2b3-9442-4b86-a50f-a81b266b727a.png)

**Comment by healergyl** [comment]
resolved
