### ISSUE TITLE
The total balance is sufficient but the invoice cannot be paid

### ISSUE THREAD

**Issue by progressorTCH** [omnilaboratory/OBAndroid#86]
When I have two channels, the balance of channel 1 is 0.00031398, the balance of channel 2 is 0.0000653, and the total balance is 0.00037928. At this time, I want to pay an invoice with a quantity of 0.00035, but the payment fails, and the failure prompts Timeout No route could be found.
![image](https://user-images.githubusercontent.com/52437247/232719387-a4b2560c-bdd9-45cd-b268-a0c48bfea19c.png)
![image](https://user-images.githubusercontent.com/52437247/232719464-adfe1d7a-96a0-4e32-b453-f41420352684.png)
![image](https://user-images.githubusercontent.com/52437247/232719533-f1da071d-4290-4732-85fb-4dae6e9a487b.png)

**Comment by neocarmack** [comment]
wait for MPP(multi path payment) of obd.

**Comment by healergyl** [comment]
resolved

**Comment by wxf4150** [comment]
the sender must reserve 10% of the channel'cap. it's lnd's protocol.
