### ISSUE TITLE
The default block is wrong

### ISSUE THREAD

**Issue by progressorTCH** [omnilaboratory/OBAndroid#88]
The default blocks is wrong when chose "slow" and medium
![image](https://user-images.githubusercontent.com/52437247/232948556-dc785459-d9df-4ed0-bb88-5f2b0fda261d.png)
![image](https://user-images.githubusercontent.com/52437247/232948580-5bf6d2a6-c2bd-41ef-97e5-c2e68322445f.png)

**Comment by healergyl** [comment]
resolved
