### ISSUE TITLE
The current recovery wallet on the main network does not have the function of recovery channel

### ISSUE THREAD

**Issue by progressorTCH** [omnilaboratory/OBAndroid#89]
Because the recovery channel needs to use the forceClose method, there is no such method on the omni main network, so the current main network recovery wallet does not have the recovery channel function
**Solution discussion**

**Comment by healergyl** [comment]
resolved

**Comment by progressorTCH** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
