### ISSUE TITLE
Should have a proper prompt when paying an invoice that was created myself

### ISSUE THREAD

**Issue by iamgamelover** [omnilaboratory/OBAndroid#96]
I created an invoice, and pasted it into the input box on the Pay Invoice popup window. When I clicked the 'NEXT' button, there is a message: 'You have not created a channel for this asset. Please create at least one channel...'

I think there should have a proper prompt when paying an invoice that was created myself.
Like this 'You can not pay an invoice that was created yourself'.

**Comment by healergyl** [comment]
After opening the channel to pay, there will be a reminder not to pay yourself
